### ISSUE TITLE
convert failure. boost::cnv::strtol  exception

### ISSUE THREAD

**Issue by liujingliangPacs** [boostorg/convert#41] opened 2019-03-19 07:27 UTC
boost::cnv::strtol cnv;
std::string str = "0";
auto intValue = boost::convert<uint32_t>(
    str,
    cnv
    (boost::cnv::parameter::skipws = true)
    (boost::cnv::parameter::base = boost::cnv::base::hex)
    ).value();
this sentence will trigger exception.

**Comment by yet-another-user** [comment] 2019-03-19 10:47
Thank you for reporting. I'll look into it ASAP.

**Comment by yet-another-user** [comment] 2019-03-19 22:02
I can't reproduce it with gcc 7.3.0. What do you use? Would you mind trying with char const* str = "0"; please? Thanks much.

**Comment by yet-another-user** [comment] 2020-09-12 21:03
I can't see any progress with the issue. So, I guess, it is not an issue anymore. Closing.

**Closed by yet-another-user** 2020-09-12 21:03 UTC
